### PR TITLE
chore(submodule): not sync with .git/config when init project

### PR DESCRIPTION
**Pull request by hangleang**

### CODE REVIEW

**Comment by PaulRBerg** [comment]
Hey @hangleang, would you mind explaining what this PR does?

**Comment by hangleang** [comment]
Hi @PaulRBerg, I did use your template for most of my works with solidity, really really thank for build this up.

by the way, the problem is when I publish the source code into git repository, those dependencies within the lib module is not sync with submodules, instead it show as a normal folder. 

when I log the config of git repo by command `git config --list`, it's not show any submodule. I guess it's not sync with those submodules.

**Comment by hangleang** [comment]
Below is the two repo init from this template and my fork PR:

- this template: https://github.com/hangleang/foundry-template-test
- this fork PR: https://github.com/hangleang/foundry-template-demo

**Comment by PaulRBerg** [comment]
Thank you for explaining.

Unfortunately, I cannot find any issue with the current format of the `.gitmodules` file. See my [conversation with ChatGPT](https://chat.openai.com/share/854807c0-3bf5-4ee1-91cb-2c0addf1c471).

It looks like there is an issue with your particular machine and installation of git. Or maybe you just need to [reset your submodules](https://twitter.com/PaulRBerg/status/1629425771457531905)?

**Comment by hangleang** [comment]
> It looks like there is an issue with your particular machine and installation of git. Or maybe you just need to [reset your submodules](https://twitter.com/PaulRBerg/status/1629425771457531905)?

Ohh that might be the problem of git initialization with my machine, thank for your suggestion. 

I'll close the issue for now.

**Comment by PaulRBerg** [comment]
@n00b21337 this template is no longer using submodules.

https://twitter.com/PaulRBerg/status/1736694426578137247

**Pull request closed without merging**
