### PR TITLE
chore: add gitpod config

### PR DESCRIPTION
**Pull request by ahmedali8**
#41

### CODE REVIEW

**Comment by ahmedali8** [comment]
Reference: https://github.com/foundry-rs/foundry/discussions/6689

**Comment by ahmedali8** [comment]
Apparently while running `bun install` forge-std is not installed

image

thus the error:

image

**Comment by PaulRBerg** [comment]
Thanks for the PR, @ahmedali8!

Such a shame that Bun didn't work .. does it work if you change the git reference to `v1.7.5` instead of `v1`?

Related: https://github.com/oven-sh/bun/issues/5870

**Comment by ahmedali8** [comment]
Yup it works!

image


image

**Comment by PaulRBerg** [comment]
Great! Thanks for your contribution. Merging now.

**Pull request merged**
